### ISSUE TITLE
Explanation / ToDos

### ISSUE THREAD

**Issue by Per-Starke** [perstarke-webdev/dates.arc42.de-site#2]
# Subtle-ads frontend and backend

This site is the frontend for the arc42 subtle-ads. It currently is visible under [test123domain123.de](https://test123domain123.de).  
I recommend publishing it under dates.arc42.org, so you have a specific training dates page, that can be referenced e.g. while displaying a message that the backend data is loading, when integrated on various sites. 

## how to integrate on websites & update dates
Information about this can be found in [the readme of the backend](https://github.com/perstarke-webdev/arc42-subtle-ads-backend).

## Testing
As you can see in the frontend, integration works well.  
I've tested this locally, and made the frontend dates page available online, both works perfectly fine.  
I have furthermore locally tested this on several of the arc42 sites that currently contain the subtle-ads submodule, like faq.arc42.org, but have not deployed that online, because I'll wait for feedback for that. Locally, on all sites I've tested this on, it worked fine.  
I've tested the dates page on Chrome, Firefox and Safari on Desktop and on Safari and Ecosia on Mobile, so different devices and browsers, all worked great. 

## ToDo
- [x] Make this frontend page available under dates.arc42.org
- [x] Please check if all of this is fine for you or you want any changes
- [x] Update all arc42-sites where the submodule is included to using the backend

**Comment by gernotstarke** [comment]
yes, nice work, and awesome you could get your hands on working with vercel.
Do you have the credentials for adding the dates.arc42.org subdomain, or do I have to do that myself?

**Comment by Per-Starke** [comment]
## Integrate into arc42-sites

- [x] faq
- [x] docs
- [x] arc42.org
- [x] Softwareknigge

**Comment by Per-Starke** [comment]
Update URL to training site from sites where this is added
